name: movie_finder
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.0
  auto_route: ^9.2.2
  get_it: ^8.0.2
  dio: ^5.0.0
  flutter_gen: ^5.8.0
  equatable: ^2.0.7
  google_fonts: ^6.2.1
  connectivity_plus: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^9.0.0
  flutter_gen_runner: ^5.8.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
